export const CLIENT_ID = 'UDWNEC1TN3J5KEE3EPVMCNYRJQBM4AKSINGEIKDEVUYH1GW3';
export const CLIENT_SECRET = 'C1ZY0BWVXFJKXASTKG0P1UQLWLNIUEEK5UZDXHNMMGHSVJRB';
export const GOOGLE_MAPS = 'AIzaSyA8I5G27ZPgsb5oVTpwOchOM3DJY0B-qhc'
export const TOKEN_NAME = 'SQUARE_USER_TOKEN';
export const API_URL = 'https://api.foursquare.com/v2';
